"""Compiles the Presenter's depth-pass shaders and embeds them in src/platform/scene_shaders.inc.

    python src/platform/shaders/build_shaders.py --dxc <dxc.exe> --glslang <glslang.exe>

dxc: the DirectX Shader Compiler (the Windows SDK's, with dxil.dll beside it so the DXIL is signed).
glslang: Khronos glslang (github.com/KhronosGroup/glslang releases). The Metal shader is embedded as
source; SDL compiles it at run time. Only needed after editing a shader: the build uses the .inc.
"""
import argparse
import pathlib
import subprocess
import tempfile

HERE = pathlib.Path(__file__).resolve().parent
OUT = HERE.parent / 'scene_shaders.inc'


def compile_all(dxc, glslang):
    blobs = {}
    with tempfile.TemporaryDirectory() as tmp:
        tmp = pathlib.Path(tmp)
        for name, profile, entry in (('kSceneVertexDxil', 'vs_6_0', 'vs_main'), ('kScenePixelDxil', 'ps_6_0', 'ps_main')):
            out = tmp / (name + '.dxil')
            subprocess.run([dxc, '-nologo', '-T', profile, '-E', entry, '-O3', '-Fo', str(out), str(HERE / 'scene.hlsl')],
                           check=True)
            blobs[name] = out.read_bytes()
        for name, src in (('kSceneVertexSpirv', 'scene.vert'), ('kScenePixelSpirv', 'scene.frag')):
            out = tmp / (name + '.spv')
            subprocess.run([glslang, '-V', '--quiet', '-o', str(out), str(HERE / src)], check=True)
            blobs[name] = out.read_bytes()
    return blobs


def c_array(name, data):
    lines = [f'inline constexpr unsigned char {name}[] = {{']
    for i in range(0, len(data), 20):
        lines.append('    ' + ', '.join(f'0x{b:02x}' for b in data[i:i + 20]) + ',')
    lines.append('};')
    return '\n'.join(lines)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--dxc', required=True)
    ap.add_argument('--glslang', required=True)
    args = ap.parse_args()
    blobs = compile_all(args.dxc, args.glslang)
    metal = (HERE / 'scene.metal').read_text(encoding='utf-8')
    assert ')MSL"' not in metal
    parts = ['// Generated by src/platform/shaders/build_shaders.py from scene.hlsl, scene.vert, scene.frag and',
             '// scene.metal: the Presenter\'s depth-pass shaders. Don\'t edit; rerun the script.',
             '#pragma once', '']
    parts += [c_array(name, data) + '\n' for name, data in blobs.items()]
    parts.append('inline constexpr char kSceneMetal[] = R"MSL(' + metal + ')MSL";')
    OUT.write_text('\n'.join(parts) + '\n', encoding='utf-8', newline='\n')
    print(f'wrote {OUT} ({", ".join(f"{k} {len(v)} bytes" for k, v in blobs.items())})')


if __name__ == '__main__':
    main()
