#pragma once
// The object editor's toolbar and view-control icons: 16 x 16 pixels, a character each. '.' is clear;
// the others are colours the editor maps (w light, g mid grey, d dark grey, y gold, r red, c cyan).

namespace vette::ui::icons {

using Icon = const char* const[16];

inline constexpr Icon kUndo = {
    "................",
    "................",
    "................",
    "....w...........",
    "...ww...........",
    "..wwwwwwwwww....",
    "...ww......ww...",
    "....w........w..",
    ".............w..",
    ".............w..",
    "............w...",
    "..wwwwwwwwww....",
    "................",
    "................",
    "................",
    "................",
};

inline constexpr Icon kMove = {
    "................",
    ".......ww.......",
    "......wwww......",
    ".....wwwwww.....",
    ".......ww.......",
    "...w...ww...w...",
    "..ww...ww...ww..",
    ".wwwwwwwwwwwwww.",
    ".wwwwwwwwwwwwww.",
    "..ww...ww...ww..",
    "...w...ww...w...",
    ".......ww.......",
    ".....wwwwww.....",
    "......wwww......",
    ".......ww.......",
    "................",
};

inline constexpr Icon kTurn = {
    "................",
    ".....wwwwww.....",
    "...ww......ww...",
    "..w..........w..",
    ".w............w.",
    ".w.........yyyyy",
    "w...........yyy.",
    "w............y..",
    "w...............",
    "w...............",
    ".w............w.",
    ".w............w.",
    "..w..........w..",
    "...ww......ww...",
    ".....wwwwww.....",
    "................",
};

inline constexpr Icon kScale = {
    "................",
    ".wwwwwwwwwwwwww.",
    ".w.......wwww.w.",
    ".w........www.w.",
    ".w.......w.ww.w.",
    ".w......w...w.w.",
    ".w.....w......w.",
    ".w....w.......w.",
    ".yyyyyy.......w.",
    ".yyyyyy.......w.",
    ".yyyyyy.......w.",
    ".yyyyyy.......w.",
    ".yyyyyy.......w.",
    ".yyyyyy.......w.",
    ".wwwwwwwwwwwwww.",
    "................",
};

inline constexpr Icon kSnap = {
    "................",
    "................",
    "..wwww....wwww..",
    "..wwww....wwww..",
    "..rrrr....rrrr..",
    "..rrrr....rrrr..",
    "..rrrr....rrrr..",
    "..rrrr....rrrr..",
    "..rrrr....rrrr..",
    "..rrrrr..rrrrr..",
    "...rrrrrrrrrr...",
    "....rrrrrrrr....",
    "......rrrr......",
    "................",
    "................",
    "................",
};

inline constexpr Icon kSymmetry = {
    "................",
    ".......cc.......",
    ".......cc.......",
    "......y..w......",
    ".....yyccww.....",
    ".....yyccww.....",
    "....yyy..w.w....",
    "....yyyccw.w....",
    "...yyyyccw..w...",
    "...yyyy..w..w...",
    "..yyyyyccw...w..",
    "..yyyyyccw...w..",
    ".yyyyyy..wwwwww.",
    ".......cc.......",
    ".......cc.......",
    "................",
};

inline constexpr Icon kVertices = {
    "................",
    ".yy..........yy.",
    ".yyddddddddddyy.",
    "..d..........d..",
    "..d..........d..",
    "..d..........d..",
    "..d..........d..",
    "..d..........d..",
    "..d..........d..",
    "..d..........d..",
    "..d..........d..",
    "..d..........d..",
    "..d..........d..",
    ".yyddddddddddyy.",
    ".yy..........yy.",
    "................",
};

inline constexpr Icon kFaces = {
    "................",
    ".wwwwwwwwwwwwww.",
    ".wyyyyyyyyyyyyw.",
    ".wyyyyyyyyyyyyw.",
    ".wyyyyyyyyyyyyw.",
    ".wyyyyyyyyyyyyw.",
    ".wyyyyyyyyyyyyw.",
    ".wyyyyyyyyyyyyw.",
    ".wyyyyyyyyyyyyw.",
    ".wyyyyyyyyyyyyw.",
    ".wyyyyyyyyyyyyw.",
    ".wyyyyyyyyyyyyw.",
    ".wyyyyyyyyyyyyw.",
    ".wyyyyyyyyyyyyw.",
    ".wwwwwwwwwwwwww.",
    "................",
};

inline constexpr Icon kNewVertex = {
    "................",
    "...........w....",
    "...........w....",
    ".........wwwww..",
    "...........w....",
    "...........w....",
    "................",
    "................",
    "....yyyy........",
    "...yyyyyy.......",
    "...yyyyyy.......",
    "...yyyyyy.......",
    "...yyyyyy.......",
    "....yyyy........",
    "................",
    "................",
};

inline constexpr Icon kNewFace = {
    "................",
    ".......yy.......",
    ".......yy.......",
    "......gggg......",
    "......gggg......",
    ".....gggggg.....",
    ".....gggggg.....",
    "....gggggggg....",
    "....gggggggg....",
    "...gggggggggg...",
    "...gggggggggg...",
    "..gggggggggggg..",
    ".yyggggggggggyy.",
    ".yyggggggggggyy.",
    "................",
    "................",
};

inline constexpr Icon kExtrude = {
    ".......ww.......",
    "......wwww......",
    ".....wwwwww.....",
    ".......ww.......",
    ".......ww.......",
    "..yyyyyyyyyyyy..",
    "..yyyyyyyyyyyy..",
    "..g..........g..",
    "..g..........g..",
    "..g..........g..",
    "..g..........g..",
    "..dddddddddddd..",
    "..dddddddddddd..",
    "................",
    "................",
    "................",
};

inline constexpr Icon kFlip = {
    "................",
    "................",
    "....w...........",
    "...ww...........",
    "..wwwwwwwwwwww..",
    "...ww...........",
    "....w...........",
    "................",
    "................",
    "...........y....",
    "...........yy...",
    "..yyyyyyyyyyyy..",
    "...........yy...",
    "...........y....",
    "................",
    "................",
};

inline constexpr Icon kMirror = {
    "................",
    ".......cc.......",
    "......w..y......",
    ".....ww..yy.....",
    "....wwwccyyy....",
    "...wwwwccyyyy...",
    "..wwwww..yyyyy..",
    ".wwwwwwccyyyyyy.",
    ".......cc.......",
    "................",
    "..........g.....",
    "..........gg....",
    "..ggggggggggg...",
    "..........gg....",
    "..........g.....",
    "................",
};

inline constexpr Icon kDelete = {
    "................",
    "................",
    "..rr........rr..",
    "..rrr......rrr..",
    "...rrr....rrr...",
    "....rrr..rrr....",
    ".....rrrrrr.....",
    "......rrrr......",
    "......rrrr......",
    ".....rrrrrr.....",
    "....rrr..rrr....",
    "...rrr....rrr...",
    "..rrr......rrr..",
    "..rr........rr..",
    "................",
    "................",
};

inline constexpr Icon kQuad = {
    "................",
    ".wwwwww..wwwwww.",
    ".w....w..w....w.",
    ".w....w..w....w.",
    ".w....w..w....w.",
    ".w....w..w....w.",
    ".wwwwww..wwwwww.",
    "................",
    "................",
    ".wwwwww..yyyyyy.",
    ".w....w..y....y.",
    ".w....w..y....y.",
    ".w....w..y....y.",
    ".w....w..y....y.",
    ".wwwwww..yyyyyy.",
    "................",
};

inline constexpr Icon kFrame = {
    "................",
    ".www........www.",
    ".w............w.",
    ".w............w.",
    "................",
    ".....gggggg.....",
    ".....gggggg.....",
    ".....gggggg.....",
    ".....gggggg.....",
    ".....gggggg.....",
    ".....gggggg.....",
    "................",
    ".w............w.",
    ".w............w.",
    ".www........www.",
    "................",
};

inline constexpr Icon kZoomIn = {
    "................",
    "...wwwwww.......",
    "..w......w......",
    ".w...yy...w.....",
    ".w...yy...w.....",
    ".w.yyyyyy.w.....",
    ".w.yyyyyy.w.....",
    ".w...yy...w.....",
    ".w...yy...w.....",
    "..w......w......",
    "...wwwwwwg......",
    ".........ggg....",
    "..........ggg...",
    "...........ggg..",
    "............gg..",
    "................",
};

inline constexpr Icon kZoomOut = {
    "................",
    "...wwwwww.......",
    "..w......w......",
    ".w........w.....",
    ".w........w.....",
    ".w.yyyyyy.w.....",
    ".w.yyyyyy.w.....",
    ".w........w.....",
    ".w........w.....",
    "..w......w......",
    "...wwwwwwg......",
    ".........ggg....",
    "..........ggg...",
    "...........ggg..",
    "............gg..",
    "................",
};

inline constexpr Icon kPan = {
    "................",
    "......ww........",
    "...ww.ww.ww.....",
    "...ww.ww.ww.ww..",
    "...ww.ww.ww.ww..",
    "...ww.ww.ww.ww..",
    "...ww.ww.ww.ww..",
    "...wwwwwwwwwww..",
    "ww.wwwwwwwwwww..",
    ".wwwwwwwwwwwww..",
    "..wwwwwwwwwwww..",
    "...wwwwwwwwwww..",
    "....wwwwwwwww...",
    ".....wwwwwww....",
    ".....wwwwwww....",
    "................",
};

inline constexpr Icon kOrbit = {
    "................",
    "................",
    "...........y....",
    "....wwwwwwwyy...",
    "..ww.......yyy..",
    ".w............w.",
    "w......yy......w",
    "w......yy......w",
    ".w............w.",
    "..ww........ww..",
    "....wwwwwwww....",
    "................",
    "................",
    "................",
    "................",
    "................",
};

}  // namespace vette::ui::icons
